#!/bin/env bash
killall -9 albert blueberry-tray caffeine-ng-git dunst emacs fctix feh flameshot gammy kmix lxsession mpDris2 mpd nm-applet obs parcellite picom polybar sxhkd udiskie ufw variety xbanish xfce4-power-manager || true

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

#Find out your monitor name with xrandr or arandr (save and you get this line)
#xrandr --output VGA-1 --primary --mode 1360x768 --pos 0x0 --rotate normal
#xrandr --output DP2 --primary --mode 1920x1080 --rate 60.00 --output LVDS1 --off &
#xrandr --output LVDS1 --mode 1366x768 --output DP3 --mode 1920x1080 --right-of LVDS1
#xrandr --output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off
#autorandr horizontal

$HOME/.config/polybar/launch.sh &

#change your keyboard if you need it
#setxkbmap -layout be

keybLayout=$(setxkbmap -v | awk -F "+" '/symbols/ {print $2}')

if [ $keybLayout = "be" ]; then
  run sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc-azerty &
else
  run sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &
fi

#Some ways to set your wallpaper besides variety or nitrogen
#feh --bg-scale ~/.config/bspwm/wall.png &
feh --bg-fill /usr/share/backgrounds/archlinux/arch-wallpaper.jpg &
feh --bg-fill /usr/share/backgrounds/arcolinux/arco-wallpaper.jpg &
#wallpaper for other Arch based systems
#feh --bg-fill /usr/share/archlinux-tweak-tool/data/wallpaper/wallpaper.png &
#feh --randomize --bg-fill ~/Dropbox/Apps/Desktoppr/*

dex $HOME/.config/autostart/arcolinux-welcome-app.desktop
xsetroot -cursor_name left_ptr &

conky -c $HOME/.config/bspwm/system-overview &
run variety &
run nm-applet &
run pamac-tray &
run xfce4-power-manager &
numlockx on &
blueberry-tray &
picom --config $HOME/.config/bspwm/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
run caffeine &

/usr/bin/emacs --daemon & || true
albert & || true
blueberry-tray & || true
caffeine-ng-git & || true
dex $HOME/.config/autostart/arcolinux-welcome-app.desktop & || true
dunst -config $HOME/.config/dunst/dunstrc & || true
edges & || true
fcitx -d & || true
flameshot & || true
gammy & || true
ufw & || true
kmix & || true
ksuperkey -e 'Super_L=Alt_L|F1' & || true
ksuperkey -e 'Super_R=Alt_L|F1' & || true
lxsession & || true
mpDris2 & || true
mpd & || true
nm-applet & || true
obs --minimize-to-tray & || true
parcellite & || true
pgrep -x sxhkd > /dev/null || sxhkd & || true
polybar -q main -c ~/.config/polybar/grayblocks.ini & || true
udiskie & || true
variety & || true
picom --config $HOME/.xmonad/picom.conf & || true
xbanish & || true
xfce4-power-manager & || true
xmodmap ~/.config/X11/xmodmap & || true
xrdb ~/.Xresources & || true
xsetroot -cursor_name left_ptr & || true

session=$DESKTOP_SESSION
case $session in
    bspwm)  echo -ne "
swipe_threshold 0
gesture swipe left  4   spectacle -r -n # capture selected region
gesture swipe right 4   bash $HOME/.config/.scripts/nightmode.sh
gesture swipe up    3   xdotool key alt+space  #launch albert
gesture swipe down  3   tdrop -am -w 60% -h 50% -y 25% -x 20% kitty # show terminal scratchpaD
gesture swipe down  4   bash $HOME/.config/.scripts/powermenu/powermenu.sh #powermenu
gesture swipe up    4   emacsclient -c -a 'emacs' # launch emacsclient
gesture swipe left  3   bspc desktop -f next.local #next desktop
gesture swipe right 3   bspc desktop -f prev.local #previous desktop
gesture pinch in    3   bspc node -c # close focused window
gesture pinch out   3   bspc node focused -g hidden=on # HIDE FOCUSED" > $HOME/.config/libinput-gestures.conf ;;
    plasma) echo -ne "
swipe_threshold 0
gesture swipe left 4 xdotool key alt+Right
gesture swipe right 4 xdotool key alt+Left
gesture swipe up 3 qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Expose'
gesture swipe down 3 qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'ShowDesktopGrid'
gesture swipe down 4 qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Window Minimize'
gesture swipe up 4 qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Window Maximize'
gesture swipe left 3 qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Switch to Next Desktop'
gesture swipe right 3 qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Switch to Previous Desktop'
gesture pinch in 3 xkill
gesture pinch out 3 xdotool key alt+0xffbe" > $HOME/.config/libinput-gestures.conf ;;
    *)   ;;
esac

